// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uruagoabebytjvfrkits.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVydWFnb2FiZWJ5dGp2ZnJraXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDYxMTksImV4cCI6MjA2NDg4MjExOX0.oZW-UPv3ja2t4p6jQLecQzcBn_BNDfHR0Wd8qHwxAvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);